version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout

      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Install node dependencies
          command: npm i --no-package-lock
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test-static:
    docker:
      - image: circleci/node:8.7-browsers
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Test
          command: ./node_modules/ember-cli/bin/ember test

  deploy-static:
    docker:
      - image: circleci/node:8.7
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: node-deps-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}
      - run:
          name: Deploy to S3
          command: |
            if [[ "${CIRCLE_BRANCH}" == "demo" ]]; then
              env | sed -n 's/^DEMO_//p' > .env
              ./node_modules/ember-cli/bin/ember deploy demo --verbose --activate
            elif grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+" <<< "$CIRCLE_TAG"; then
              env | sed -n 's/^PROD_//p' > .env
              ./node_modules/ember-cli/bin/ember deploy production --verbose --activate
            fi

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deploy-{{ checksum "circle.yml" }}
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/.venv ]]; then
              python3 -m venv ~/.venv
              source ~/.venv/bin/activate
              pip3 install -U git+https://github.com/nypublicradio/nyprsetuptools.git
            fi
      - deploy:
          command: |
            source ~/.venv/bin/activate
            if [[ "${CIRCLE_BRANCH}" == "demo" ]]; then
              nyprsetuptools DockerDeploy --environment=demo \
                                          --ecs-cluster=fastboot \
                                          --ecr-repository=crowdsourcing-fastboot \
                                          --test='npm test' \
                                          --tag=demo \
                                          --wait=300
            elif echo "$CIRCLE_TAG" | grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+"; then
              nyprsetuptools DockerDeploy --environment=prod \
                                          --ecs-cluster=fastboot \
                                          --ecr-repository=crowdsourcing-fastboot \
                                          --test='npm test' \
                                          --tag="$CIRCLE_TAG" \
                                          --wait=300
            fi
      - save_cache:
          key: deploy-{{ checksum "circle.yml" }}
          paths:
            - ~/.venv

workflows:
  version: 2
  buld-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - deploy:
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]+/
            branches:
              only: demo
      - deploy-static:
          requires:
            - test-static
          filters:
            tags:
              only: /^v[0-9]\.[0-9]\.[0-9]+/
            branches:
              only: demo
