version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8
      environment:
        JOBS: 2

node_key: &node_key
  key: node-deps-v4-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

restore_node: &restore_node
  restore_cache:
    <<: *node_key

static_deploy_steps: &static_deploy_steps
  steps:
    - checkout
    - <<: *restore_node
    - run:
        name: Deploy to S3
        command: |
          env | sed -n "s/^"$ENV"_//p" > .env
          npx ember deploy `echo $ENV | tr A-Z a-z` --verbose --activate

fastboot_deploy: &fastboot_deploy
  docker:
    - image: circleci/python:3.6
  steps:
    - checkout
    - setup_remote_docker
    - restore_cache:
        key: deploy-{{ checksum "circle.yml" }}
    - run:
        name: Install Requirements
        command: |
          if [[ ! -d ~/.venv ]]; then
            python3 -m venv ~/.venv
            source ~/.venv/bin/activate
            pip3 install -U git+https://github.com/nypublicradio/nyprsetuptools.git
          fi
    - deploy:
        command: |
          TAG=${CIRCLE_TAG:-demo}
          source ~/.venv/bin/activate
          nyprsetuptools DockerDeploy --environment=$ENV \
                                      --ecs-cluster=fastboot \
                                      --ecr-repository=crowdsourcing-fastboot \
                                      --tag=$TAG \
                                      --wait=300 \
                                      --fargate \
                                      --execution-role=crowdsourcing-fastboot-$ENV \
                                      --ports=3000 \
                                      --cpu=256 \
                                      --memory-reservation=512
    - save_cache:
        key: deploy-{{ checksum "circle.yml" }}
        paths:
          - ~/.venv

jobs:
  build-static:
    <<: *defaults

    steps:
      - checkout

      - <<: *restore_node

      - run:
          name: Install node dependencies
          command: npm ci
      - save_cache:
          <<: *node_key
          paths:
            - ./node_modules

  test-static:
    docker:
      - image: circleci/node:8-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - <<: *restore_node

      - run:
          name: Test
          command: npx ember test

  deploy-static-prod:
    environment:
      ENV: PROD

    <<: *defaults
    <<: *static_deploy_steps

  deploy-static-demo:
    environment:
      ENV: DEMO

    <<: *defaults
    <<: *static_deploy_steps

  deploy-fastboot-demo:
    environment:
      ENV: demo

    <<: *fastboot_deploy

  deploy-fastboot-prod:
    environment:
      ENV: prod

    <<: *fastboot_deploy


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-static
      - test-static:
          requires:
            - build-static

  deploy-demo:
    jobs:
      - build-static:
          filters:
            branches:
              only: master
      - test-static:
          requires:
            - build-static
      - deploy-static-demo:
          requires:
            - test-static
      - deploy-fastboot-demo:
          requires:
            - deploy-static-demo

  deploy-prod:
    jobs:
      - build-static:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - test-static:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - build-static

      - deploy-static-prod:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - test-static
      - deploy-fastboot-prod:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
          requires:
            - deploy-static-prod
